[2025-09-07T00:00:23.038+0000] {processor.py:186} INFO - Started process (PID=3963) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:00:23.039+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:00:23.040+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:00:23.040+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:00:23.044+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:00:23.043+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:00:23.044+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:00:23.067+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.036 seconds
[2025-09-07T00:00:53.831+0000] {processor.py:186} INFO - Started process (PID=4029) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:00:53.832+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:00:53.834+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:00:53.834+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:00:53.840+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:00:53.839+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:00:53.841+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:00:53.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.041 seconds
[2025-09-07T00:01:23.998+0000] {processor.py:186} INFO - Started process (PID=4095) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:01:23.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:01:24.002+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:01:24.002+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:01:24.009+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:01:24.007+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:01:24.009+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:01:24.031+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.038 seconds
[2025-09-07T00:01:54.858+0000] {processor.py:186} INFO - Started process (PID=4160) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:01:54.859+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:01:54.862+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:01:54.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:01:54.869+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:01:54.867+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:01:54.870+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:01:54.893+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.040 seconds
[2025-09-07T00:02:25.743+0000] {processor.py:186} INFO - Started process (PID=4226) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:02:25.744+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:02:25.746+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:02:25.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:02:25.753+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:02:25.751+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:02:25.753+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:02:25.775+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.037 seconds
[2025-09-07T00:02:56.637+0000] {processor.py:186} INFO - Started process (PID=4292) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:02:56.638+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:02:56.640+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:02:56.640+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:02:56.650+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:02:56.649+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:02:56.650+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:02:56.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.037 seconds
[2025-09-07T00:03:27.403+0000] {processor.py:186} INFO - Started process (PID=4358) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:03:27.406+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:03:27.409+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:03:27.409+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:03:27.416+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:03:27.414+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:03:27.417+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:03:27.442+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.046 seconds
[2025-09-07T00:03:57.771+0000] {processor.py:186} INFO - Started process (PID=4424) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:03:57.773+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:03:57.775+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:03:57.774+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:03:57.781+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:03:57.779+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:03:57.782+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:03:57.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.034 seconds
[2025-09-07T00:04:28.091+0000] {processor.py:186} INFO - Started process (PID=4490) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:04:28.107+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:04:28.129+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:04:28.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:04:28.195+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:04:28.178+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:04:28.228+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:04:28.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.412 seconds
[2025-09-07T00:04:58.723+0000] {processor.py:186} INFO - Started process (PID=4551) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:04:58.724+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:04:58.725+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:04:58.725+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:04:58.729+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:04:58.728+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:04:58.729+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:04:58.745+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.029 seconds
[2025-09-07T00:05:29.386+0000] {processor.py:186} INFO - Started process (PID=4617) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:05:29.387+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:05:29.390+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:05:29.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:05:29.396+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:05:29.394+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:05:29.396+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:05:29.412+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.030 seconds
[2025-09-07T00:05:59.593+0000] {processor.py:186} INFO - Started process (PID=4682) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:05:59.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:05:59.597+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:05:59.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:05:59.603+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:05:59.601+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:05:59.604+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:05:59.628+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.043 seconds
[2025-09-07T00:06:30.216+0000] {processor.py:186} INFO - Started process (PID=4741) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:06:30.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:06:30.218+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:06:30.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:06:30.222+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:06:30.221+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:06:30.223+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:06:30.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.032 seconds
[2025-09-07T00:07:00.819+0000] {processor.py:186} INFO - Started process (PID=4807) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:07:00.821+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:07:00.824+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:07:00.824+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:07:00.830+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:07:00.828+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:07:00.831+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:07:00.852+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.038 seconds
[2025-09-07T00:07:31.262+0000] {processor.py:186} INFO - Started process (PID=4873) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:07:31.263+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:07:31.265+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:07:31.265+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:07:31.276+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:07:31.274+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:07:31.277+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:07:31.295+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.038 seconds
[2025-09-07T00:08:01.846+0000] {processor.py:186} INFO - Started process (PID=4939) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:08:01.847+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:08:01.850+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:08:01.850+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:08:01.854+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:08:01.853+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:08:01.855+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:08:01.870+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.029 seconds
[2025-09-07T00:08:31.929+0000] {processor.py:186} INFO - Started process (PID=5005) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:08:31.930+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:08:31.933+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:08:31.933+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:08:31.938+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:08:31.937+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:08:31.939+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:08:31.956+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.032 seconds
[2025-09-07T00:09:02.122+0000] {processor.py:186} INFO - Started process (PID=5071) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:09:02.123+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:09:02.125+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:09:02.124+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:09:02.130+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:09:02.129+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:09:02.131+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:09:02.153+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.038 seconds
[2025-09-07T00:09:33.015+0000] {processor.py:186} INFO - Started process (PID=5137) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:09:33.016+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:09:33.018+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:09:33.018+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:09:33.022+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:09:33.021+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:09:33.022+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:09:33.040+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.030 seconds
[2025-09-07T00:10:03.290+0000] {processor.py:186} INFO - Started process (PID=5203) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:10:03.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:10:03.294+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:10:03.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:10:03.299+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:10:03.298+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:10:03.300+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:10:03.322+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.037 seconds
[2025-09-07T00:10:34.008+0000] {processor.py:186} INFO - Started process (PID=5269) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:10:34.009+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:10:34.010+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:10:34.010+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:10:34.015+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:10:34.014+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:10:34.015+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:10:34.033+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.030 seconds
[2025-09-07T00:11:04.222+0000] {processor.py:186} INFO - Started process (PID=5335) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:11:04.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:11:04.226+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:11:04.225+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:11:04.232+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:11:04.230+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:11:04.233+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:11:04.261+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.046 seconds
[2025-09-07T00:11:34.948+0000] {processor.py:186} INFO - Started process (PID=5401) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:11:34.950+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:11:34.952+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:11:34.952+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:11:34.957+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:11:34.956+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:11:34.958+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:11:34.978+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.037 seconds
[2025-09-07T00:12:05.031+0000] {processor.py:186} INFO - Started process (PID=5467) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:12:05.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:12:05.035+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:12:05.034+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:12:05.040+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:12:05.039+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:12:05.041+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:12:05.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.036 seconds
[2025-09-07T00:12:35.180+0000] {processor.py:186} INFO - Started process (PID=5532) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:12:35.182+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:12:35.184+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:12:35.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:12:35.191+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:12:35.189+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:12:35.192+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:12:35.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.040 seconds
[2025-09-07T00:13:05.955+0000] {processor.py:186} INFO - Started process (PID=5598) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:13:05.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:13:05.960+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:13:05.959+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:13:05.965+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:13:05.964+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:13:05.966+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:13:05.987+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.038 seconds
[2025-09-07T00:13:36.775+0000] {processor.py:186} INFO - Started process (PID=5664) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:13:36.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:13:36.778+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:13:36.777+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:13:36.782+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:13:36.780+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:13:36.783+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:13:36.804+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.033 seconds
[2025-09-07T00:14:07.603+0000] {processor.py:186} INFO - Started process (PID=5729) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:14:07.604+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:14:07.606+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:14:07.606+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:14:07.611+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:14:07.609+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:14:07.612+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:14:07.634+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.036 seconds
[2025-09-07T00:14:38.410+0000] {processor.py:186} INFO - Started process (PID=5788) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:14:38.411+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:14:38.413+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:14:38.412+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:14:38.416+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:14:38.415+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:14:38.416+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:14:38.432+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.030 seconds
[2025-09-07T00:15:09.081+0000] {processor.py:186} INFO - Started process (PID=5854) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:15:09.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:15:09.083+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:15:09.083+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:15:09.087+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:15:09.086+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:15:09.088+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:15:09.106+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.033 seconds
[2025-09-07T00:15:39.152+0000] {processor.py:186} INFO - Started process (PID=5920) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:15:39.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:15:39.155+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:15:39.154+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:15:39.161+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:15:39.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:15:39.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:15:39.180+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.034 seconds
[2025-09-07T00:16:09.822+0000] {processor.py:186} INFO - Started process (PID=5986) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:16:09.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:16:09.825+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:16:09.824+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:16:09.828+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:16:09.827+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:16:09.829+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:16:09.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.027 seconds
[2025-09-07T00:16:40.409+0000] {processor.py:186} INFO - Started process (PID=6051) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:16:40.411+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:16:40.412+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:16:40.412+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:16:40.416+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:16:40.415+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:16:40.416+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:16:40.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.035 seconds
[2025-09-07T00:17:11.069+0000] {processor.py:186} INFO - Started process (PID=6117) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:17:11.071+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:17:11.074+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:17:11.073+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:17:11.079+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:17:11.078+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:17:11.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:17:11.101+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.040 seconds
[2025-09-07T00:17:41.791+0000] {processor.py:186} INFO - Started process (PID=6183) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:17:41.792+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:17:41.794+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:17:41.793+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:17:41.797+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:17:41.796+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:17:41.798+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:17:41.814+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.029 seconds
[2025-09-07T00:18:12.521+0000] {processor.py:186} INFO - Started process (PID=6249) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:18:12.522+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:18:12.526+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:18:12.526+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:18:12.532+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:18:12.530+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:18:12.533+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:18:12.552+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.038 seconds
[2025-09-07T00:18:43.377+0000] {processor.py:186} INFO - Started process (PID=6315) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:18:43.379+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:18:43.382+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:18:43.380+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:18:43.386+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:18:43.385+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:18:43.387+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:18:43.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.032 seconds
[2025-09-07T00:19:13.904+0000] {processor.py:186} INFO - Started process (PID=6380) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:19:13.905+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:19:13.908+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:19:13.907+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:19:13.912+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:19:13.911+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:19:13.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:19:13.933+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.034 seconds
[2025-09-07T00:19:44.765+0000] {processor.py:186} INFO - Started process (PID=6446) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:19:44.766+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:19:44.770+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:19:44.768+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:19:44.775+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:19:44.773+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:19:44.776+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:19:44.793+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.032 seconds
[2025-09-07T00:20:15.472+0000] {processor.py:186} INFO - Started process (PID=6512) to work on /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:20:15.472+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/airbyte_test.py for tasks to queue
[2025-09-07T00:20:15.474+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:20:15.473+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:20:15.479+0000] {logging_mixin.py:190} INFO - [2025-09-07T00:20:15.477+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/airbyte_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airbyte_test.py", line 3, in <module>
    from airflow.providers.airbyte.operators.airbyte import AirbyteTriggerSyncOperator
ModuleNotFoundError: No module named 'airflow.providers.airbyte'
[2025-09-07T00:20:15.479+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/airbyte_test.py
[2025-09-07T00:20:15.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/airbyte_test.py took 0.033 seconds
